#!/bin/bash

sudo gatee

flag=false;

while read -r line
do
    if [[ -d $line ]]; then
        cd "$line"
        echo "Changed directory to $line";
        break;
    elif [[ -f $line ]]; then
        nano "$line" < /dev/tty ;
        echo "Opened $line with nano";
        flag=true;
        cd ${line%/*};
        break;
    else
        echo "ERROR.";
        break;
    fi
done < "/.gatee_cd"


if $flag ; then
    . runGatee
fi
